### ISSUE TITLE
SonarCloud support & Manual Code analysis

### ISSUE THREAD

**Issue by benedekkata** [BME-MIT-IET/iet-hf-2022-osd-kft#1]
Technológia fókusz: 

* Manuális kód átvizsgálás elvégzése az alkalmazás egy részére (GitHub, Gerrit...) + Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarCloud, SpotBugs, VS Code Analyzer, Codacy, Coverity Scan...).  
- Mivel az eszközök rengeteg hibát és figyelmeztetést találhatnak, ezért elég azok egy részét megvizsgálni és ha a csapat minden tagja egyetért vele, akkor javítani. Törekedjetek arra, hogy különböző típusú, és lehetőleg nem triviális hibajelzéseket vizsgáljatok meg.

Feladat megoldó: @benedekkata 

Ellenőrizk: @bence1922 @adambalint111 @benczeadam @vargus1111

**Comment by benedekkata** [comment]
### Manuális analízis
#### A vizsgálat tárgya

* iet-hf-2022-osd-kft/src/main/java/com/atomgraph/server mappában található kódok.

#### Talált hibák

* Kikommentelt kódrészlet maradt a kódban:
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/factory/TemplateCallFactory.java#L76>
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/mapper/SHACLConstraintViolationExceptionMapper.java#L46>

* Túl hosszú függvény
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/io/ValidatingDatasetProvider.java#L68>

* Nemhasznált tagváltozók:
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/io/SkolemizingModelProvider.java#L39>
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/io/SkolemizingDatasetProvider.java#L41>
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/factory/TemplateCallFactory.java#L45>
  
* A konstruktorba kapott paraméter nem kerül felhasználásra.
  * <https://github.com/BME-MIT-IET/iet-hf-2022-osd-kft/blob/0d4729ff55d3af59de64acd6ac753efc3d14d46b/src/main/java/com/atomgraph/server/exception/SPINConstraintViolationException.java#L31>

#### Javítandó

Minden kódrészlet, amely nem igényli a kód bonyolultabb refaktorálását

**Comment by benedekkata** [comment]
### SonarCloud analízis elemzése
#### A vizsgálat tárgya

* iet-hf-2022-osd-kft main ágán található összes kód.

#### Érdekesebb hibák

Az analízis összesen 66 Code Smell-t talált.
![image](https://user-images.githubusercontent.com/35570314/168873948-20bb4cc0-8435-4ae9-8bb8-7cb66cb4e883.png)

Assert nélküli teszt eset:
* https://sonarcloud.io/project/issues?issues=AYDPALTZcWmnrRvXvHXi&open=AYDPALTZcWmnrRvXvHXi&id=BME-MIT-IET_iet-hf-2022-osd-kft

13 beégetett szöveg ismétlés egyetlen fájlban:
(src/main/java/com/atomgraph/processor/util/Skolemizer.java)
* https://sonarcloud.io/project/issues?issues=AYDPALR6cWmnrRvXvHWt&open=AYDPALR6cWmnrRvXvHWt&id=BME-MIT-IET_iet-hf-2022-osd-kft

Kritikus hibaként észlet kisbetűs konstans változónév:
* https://sonarcloud.io/project/issues?issues=AYDPALTPcWmnrRvXvHXY&open=AYDPALTPcWmnrRvXvHXY&id=BME-MIT-IET_iet-hf-2022-osd-kft

Abstract osztály publikus konstruktorral:
* https://sonarcloud.io/project/issues?issues=AYDPALSucWmnrRvXvHXL&open=AYDPALSucWmnrRvXvHXL&id=BME-MIT-IET_iet-hf-2022-osd-kft

Blocker típusú hiba az osztály névvel ütköző, nem elég egyértelmű változónevek miatt a src/main/java/com/atomgraph/processor/vocabulary/LDT.java fájlban.
* https://sonarcloud.io/project/issues?issues=AYDPALSGcWmnrRvXvHW3&open=AYDPALSGcWmnrRvXvHW3&id=BME-MIT-IET_iet-hf-2022-osd-kft

#### Javítandó

A csapat közös döntése alapján az itt felsorolt hibák kerülnek kijavításra.

**Comment by benedekkata** [comment]
Elrontott commit message miatt hiányzó commit:

SonarCloud analízis találatok javítása: 
4a8d851dd560236e6f6f80b1dad38f635ed1de76

**Comment by benedekkata** [comment]
Javítások eredménye: 
66 -> 9 code smell

![image](https://user-images.githubusercontent.com/35570314/169159032-28aa87dd-946b-401b-8e15-a2f73bf4507f.png)

![image](https://user-images.githubusercontent.com/35570314/169158994-6427fb4d-85b4-4acd-a903-a8b06a3679c6.png)

**Comment by bence1922** [comment]
Szép munka! Ennél nagyobb refaktorálásra szerintem sincs szükség. Tökéletes így a megodás. @adambalint111 és én is átnéztük a pull requestet.
