### ISSUE TITLE
Build framework settings

### ISSUE THREAD

**Issue by bence1922** [BME-MIT-IET/iet-hf-2022-osd-kft#4]
Technológia fókusz

- Build keretrendszer beüzemelése, ha még nincs (Maven, Gradle...) + CI beüzemelése, ha még nincs (Actions, Travis, AppVeyor, Azure Pipelines...)
- Maven keretrendszer beállítása, pom.xml javítása és bővítése.

Feladat megoldó: @bence1922

Ellenőrizk: @benczeadam @vargus1111

**Comment by bence1922** [comment]
Github workflow template-et használok: Java CI with Maven

**Comment by bence1922** [comment]
Java JDK 11-el a build sikeretelen. pom.xml-ben megkerestem, java 17-es verziót kell használni.

**Comment by bence1922** [comment]
Java 17-el sikeres a build, push-ra és PR-re fut a main branchen. Később ha valemyik csapattag szeretné bővíthetem, hogy ne csak a main  branch eseményeire fusson le.

**Comment by vargus1111** [comment]
Szép munka! Szerintem már minden jó.
