### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by bence1922** [BME-MIT-IET/iet-hf-2022-osd-kft#6]
Termék/felhasználó fókusz
- Nem-funkcionális jellemzők vizsgálata (teljesítmény, stresszteszt, biztonság, használhatóság...)

Feladat megoldó: @vargus1111 

Ellenőrzik: @adambalint111 @bence1922

**Comment by vargus1111** [comment]
Kipróbáltam először 5 másodperces küszöbértékkel, ezen a teszten nagyrészt átment.

**Comment by bence1922** [comment]
> Kipróbáltam először 5 másodperces küszöbértékkel, ezen a teszten nagyrészt átment.

Próbáld ki szerintem kisebb küszöbértékekkel is.

**Comment by vargus1111** [comment]
Kipróbáltam 500ms küszöbértékkel, ezen már javarészt elbukott.

**Comment by adambalint111** [comment]
Véletlenül rossz issue-hoz kötött commit: c83d3362bd0cf70afd8c0b482becc17bc49b1626

**Comment by benedekkata** [comment]
Megoldás a main ágra lett pusholva. Nincs minden benne a csatolt PR. Csapat elfogadta a megoldást.
