### ISSUE TITLE
Docker hub deployment

### ISSUE THREAD

**Issue by bence1922** [BME-MIT-IET/iet-hf-2022-osd-kft#8]
Technológia fókusz

- Deployment segítése (Docker, Vagrant, felhő szolgáltatásba telepítés...)
- Docker image készítés dockerfile segítségével, majd ennek deployolása docker hub-ra

Feladat megoldó: @bence1922

Ellenőrizk: @benczeadam @vargus1111

**Comment by bence1922** [comment]
Docker hubra van valakinek fiókja vagy regisztráljak?

**Comment by vargus1111** [comment]
> Docker hubra van valakinek fiókja vagy regisztráljak?

Nincs, inkább csinálj egyet

**Comment by bence1922** [comment]
Csináltam és fent a docker image, ha valaki le akarja pullolni magának otthon az image leszedése: docker pull bence1922/simplewhale

**Comment by benedekkata** [comment]
Kipróbáltam, jól működik!
